[tools]
bun = "1.2.0"
deno = "latest"
go = "1.24.4"
lua-language-server = "latest"
markdownlint-cli2 = "latest"
node = "lts"
ruff = "latest"
stylua = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:prettier-plugin-organize-imports" = "latest"
"npm:fs-extra" = "latest"
"npm:@redocly/cli" = "latest"
"npm:marksman" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
