gui:
  showIcons: true
  nerdFontsVersion: "3"
  # Use the mocha catppuccin theme (lavender)
  theme:
    activeBorderColor:
      - '#b4befe'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#b4befe'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
authorColors:
  '*': '#b4befe'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
