return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = 1000,
		lazy = false,
		opts = function()
			return {
				flavour = "mocha",
				transparent_background = true,
				float = {
					transparent = true,
					solid = true,
				},
				show_end_of_buffer = true,
				no_italic = false,
				no_bold = false,
				no_underline = false,
				styles = {
					comments = { "italic" },
					conditionals = { "italic" },
					constants = {},
					functions = { "italic" },
					keywords = {},
					numbers = {},
					operators = { "bold" },
					strings = {},
					types = {},
					variables = {},
				},
				default_integrations = false,
				auto_integrations = true,
				integrations = {
					--aerial = true,
					--alpha = true,
					bufferline = true,
					--cmp = true,
					dashboard = true,
					--flash = true,
					fzf = true,
					--grug_far = true,
					--gitsigns = true,
					--headlines = true,
					--illuminate = true,
					--indent_blankline = { enabled = true },
					--leap = true,
					lsp_saga = true,
					--lsp_trouble = true,
					--mason = true,
					--markdown = true,
					--mini = true,
					native_lsp = {
						enabled = true,
						underlines = {
							errors = { "undercurl" },
							hints = { "undercurl" },
							warnings = { "undercurl" },
							information = { "undercurl" },
						},
					},
					navic = { enabled = true, custom_bg = "NONE" },
					--neotest = true,
					--neotree = true,
					noice = true,
					notify = true,
					--semantic_tokens = true,
					--snacks = true,
					telescope = true,
					treesitter = true,
					treesitter_context = true,
					which_key = true,
				},
			}
		end,
		config = function(_, opts)
			require("catppuccin").setup(opts)
			vim.cmd.colorscheme("catppuccin")
		end,
	},
}
