# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"

# Inserts a blank line between shell prompts
add_newline = true

format = """
${custom.git_repo}\
$directory\
$git_status\
$git_branch\
$git_commit\
$git_state\
$jobs\
$status\
$cmd_duration\
$line_break\
$character\
"""

# Replace the '❯' symbol in the prompt with '➜'
[character]
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

success_symbol = '[󰞷 ](green)'
error_symbol = '[ ](red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncate_to_repo = true
truncation_length = 100
format = '[$path ]($style)[$read_only]($read_only_style)'
style = 'bold blue'
repo_root_format = '[($path )]($repo_root_style)[$read_only]($read_only_style)[-](black) '
repo_root_style = 'blue'

[custom.git_repo]
when = true
require_repo = true
command = 'git rev-parse --show-toplevel | sed -e "s,$(ghq root)/\(github\.com/\)\?,,"'
style = "bold blue"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted= '[= ](red)'
ahead = '[⇡$ahead_count ](red)'
behind = '[⇣$behind_count ](cyan)'
modified = '[ ](yellow)'
deleted = '[󱎘 ](red)'
untracked = '[ ](red)'
staged = '[󰸞 ](green)'
stashed ='[󰉀 ](cyan)'

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '
style = 'bold red'

[git_branch]
format = '[-](black) [$symbol ](bold purple)[$branch(:$remote_branch) ](bold purple)'
symbol = ''
style = 'bold purple'

[jobs]
number_threshold = 1
style = 'purple'

[status]
format = '[[-](black) $status( SIG$signal_name)]($style) '
disabled = false
style = 'red'

[cmd_duration]
format = '[[-](black) 󱦟 $duration]($style) '
style = 'yellow'
min_time = 10_000

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
