# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = true

format = """
${custom.git_repo}\
$directory\
$git_status\
$git_branch\
$git_commit\
$git_state\
$jobs\
$status\
$cmd_duration\
$line_break\
$character\
"""

# Replace the '❯' symbol in the prompt with '➜'
[character]
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

success_symbol = '[󰞷 ](green)'
error_symbol = '[ ](red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncate_to_repo = true
truncation_length = 100
format = '[$path ]($style)[$read_only]($read_only_style)'
style = 'bold blue'
repo_root_format = '[($path )]($repo_root_style)[$read_only]($read_only_style)[-](black) '
repo_root_style = 'blue'

[custom.git_repo]
when = true
require_repo = true
command = 'git rev-parse --show-toplevel | sed -e "s,$(ghq root)/\(github\.com/\)\?,,"'
style = "bold blue"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted= '[= ](red)'
ahead = '[⇡$ahead_count ](red)'
behind = '[⇣$behind_count ](cyan)'
modified = '[ ](yellow)'
deleted = '[󱎘 ](red)'
untracked = '[ ](red)'
staged = '[󰸞 ](green)'
stashed ='[󰉀 ](cyan)'

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '
style = 'bold red'

[git_branch]
format = '[-](black) [$symbol ](bold purple)[$branch(:$remote_branch) ](bold purple)'
symbol = ''
style = 'bold purple'

[jobs]
number_threshold = 1
style = 'purple'

[status]
format = '[[-](black) $status( SIG$signal_name)]($style) '
disabled = false
style = 'red'

[cmd_duration]
format = '[[-](black) 󱦟 $duration]($style) '
style = 'yellow'
min_time = 10_000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
